# -*- coding: utf-8 -*-
"""[TW] Text Generator - chinese - beta.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/xxxxxxxxxx

## Settings
it takes time to load all the packages --be patient <br>
remember to turn on GPU mode when you run the codes
"""

# Commented out IPython magic to ensure Python compatibility.
#%tensorflow_version 1.x
!pip install -I tensorflow-gpu==1.15.4 &> tmp.log
!git clone -q https://github.com/imcaspar/gpt2-ml
# %cd /content/gpt2-ml
!mkdir -p /content/gpt2-ml/models/mega

!perl 3rd/gdown.pl/gdown.pl https://drive.google.com/open?id=1mT_qCQg4AWnAXTwKfsyyRWCRpgPrBJS3 models/mega/model.ckpt-220000.data-00000-of-00001
!wget -q --show-progress https://github.com/imcaspar/gpt2-ml/releases/download/v1.0/model.ckpt-220000.index -P models/mega
!wget -q --show-progress https://github.com/imcaspar/gpt2-ml/releases/download/v1.0/model.ckpt-220000.meta -P models/mega
!echo 'Download finished.🍺'
# If gdown.pl failed, please uncomment following code & exec
!python scripts/down_gdrive_file.py -file_id='xxxxxxxxxxxx' -file_path='models/mega/model.ckpt-220000.data-00000-of-00001'

"""## Text Generator
it takes time to run Deep Learning Algorithm --be patient <br>
please insert "Chinese" only, "Simplified Chinese" has better output result
"""

min_len = 300 #param {type:"number", min:5, max:1024, step:1}
sp_num = 5    #param {type:"number", min:1, max:50, step:1}
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
!PYTHONPATH=$(pwd) python /content/gpt2-ml/scripts/demo.py -ckpt_fn models/mega/model.ckpt-220000 -min_len $min_len -samples $sp_num