# -*- coding: utf-8 -*-
"""[TW] Driver Pool 批次調整 + 半自動指派機器

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/xxxxxxxxxxxxxxxxx

# 設定 Setting
"""

#install chromium, its driver, selenium and other packages:
#!apt install chromium-chromedriver
#!cp /usr/lib/chromium-browser/chromedriver /usr/bin
!apt-get update # to update ubuntu to correctly run apt install
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin

import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')

!pip install google-auth
!pip install selenium
!pip install requests
!pip install bs4
!pip install lxml
!pip install --upgrade -q gspread
!pip install gspread_dataframe

# Set Login Account and Password
Admin_User_Email = str('xxxxxx') # Admin Panel
Admin_User_Password = str('xxxxxx')           # Admin Panel
Admin_User_Email2 = str('xxxxxx')        # Intercom
Admin_User_Password2 = str('xxxxxxx')       # Intercom

# Grant Google Access 
import os                                                                       # Mount the drive from Google to save the dataset
from google.colab import drive                                                  # this will be our driver
drive.mount('/gdrive')
root = '/gdrive/My Drive/'

from google.colab import auth
auth.authenticate_user()

import gspread
from oauth2client.client import GoogleCredentials

gc = gspread.authorize(GoogleCredentials.get_application_default())

import re
import time 
from selenium import webdriver
from bs4 import BeautifulSoup
from selenium.webdriver.support.ui import Select 
import requests 
from selenium.webdriver.common.keys import Keys 
import pandas as pd 
import numpy as np 
from datetime import timedelta 
import datetime 
close_link = 'https://docs.google.com/spreadsheets/d/1wvJ0xxxxxxxxxC3vrIQa1_FgVM/edit#gid=2113369210' 
open_link = 'https://docs.google.com/spreadsheets/d/1wvJ01xxxxxxxxC3vrIQa1_FgVM/edit#gid=1391129654'

"""# 關閉Driver Pool
此處Driver Pool指 “All Drivers” 和 “Exclude from Default Channel” 這兩處
"""

wb = gc.open_by_url(close_link)
sheet = wb.worksheet('關閉Pool')
rows = sheet.get_all_values()

cell_df = pd.DataFrame(rows[1:],columns = rows[0] )
cell_df['司機頁面'] = '-'
cell_df['Pool頁面'] = '-'
for i in range(0,len(cell_df)):
  cell_df['司機頁面'][i] = 'xxxxxxx' + str(cell_df['關閉Pool司機ID'][i]) + '/edit'
  cell_df['Pool頁面'][i] = 'xxxxxxx' + str(cell_df['關閉Pool司機ID'][i]) + '/pools'
cell_df

from selenium import webdriver
import datetime
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless') #set options to be headless
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
d = webdriver.Chrome(chrome_options=chrome_options)

d.get('xxxxxxx')  
d.find_element_by_id("admin_user_email").send_keys(Admin_User_Email)            # Admin User Email
d.find_element_by_id("admin_user_password").send_keys(Admin_User_Password)      # Admin User Password
d.find_element_by_xpath('//*[@id="admin_user_submit_action"]/input').click()
time.sleep(3)
  
for i in range(0,len(cell_df)):
  try:
    d.get(cell_df['司機頁面'][i])
    time.sleep(1)
    d.find_element_by_xpath('//*[@id="driver_exclude_from_default_channel"]').click()
    d.find_element_by_xpath('//*[@id="driver_submit_action"]/input').click()
    time.sleep(1)
    
    d.get(cell_df['Pool頁面'][i])  
    time.sleep(1)
    d.find_element_by_xpath('//*[@id="driver_driver_pool_ids_11"]').click()
    d.find_element_by_xpath('//*[@id="driver_driver_pool_ids_43"]').click()
    d.find_element_by_xpath('//*[@id="main_content"]/div/form/fieldset/input[35]').click()

    print(cell_df['關閉Pool司機ID'][i],"已關閉")
  except:
    continue

"""# 開啟Driver Pool
此處Driver Pool指 “All Drivers” 和 “Exclude from Default Channel” 這兩處
"""

wb = gc.open_by_url(open_link)
sheet2 = wb.worksheet('開啟Pool')
rows2 = sheet2.get_all_values()

cell_df2 = pd.DataFrame(rows2[1:],columns = rows2[0] )
cell_df2['司機頁面'] = '-'
cell_df2['Pool頁面'] = '-'
for i in range(0,len(cell_df2)):
  cell_df2['司機頁面'][i] = 'xxxxxxxx' + str(cell_df2['開啟Pool司機ID'][i]) + '/edit'
  cell_df2['Pool頁面'][i] = 'xxxxxxxx' + str(cell_df2['開啟Pool司機ID'][i]) + '/pools'
cell_df2

from selenium import webdriver
import datetime
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless') #set options to be headless
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
p = webdriver.Chrome(chrome_options=chrome_options)

p.get('xxxxxxxx')  
p.find_element_by_id("admin_user_email").send_keys(Admin_User_Email)            # Admin User Email
p.find_element_by_id("admin_user_password").send_keys(Admin_User_Password)      # Admin User Password
p.find_element_by_xpath('//*[@id="admin_user_submit_action"]/input').click()
time.sleep(3)
  
for i in range(0,len(cell_df2)):
  try:
    p.get(cell_df2['司機頁面'][i])
    time.sleep(1)
    p.find_element_by_xpath('//*[@id="driver_exclude_from_default_channel"]').click()
    p.find_element_by_xpath('//*[@id="driver_submit_action"]/input').click()
    time.sleep(1)
    
    p.get(cell_df2['Pool頁面'][i])  
    time.sleep(1)
    p.find_element_by_xpath('//*[@id="driver_driver_pool_ids_11"]').click()
    p.find_element_by_xpath('//*[@id="driver_driver_pool_ids_43"]').click()
    p.find_element_by_xpath('//*[@id="main_content"]/div/form/fieldset/input[35]').click()

    print(cell_df2['開啟Pool司機ID'][i],"已開啟")
  except:
    continue

"""# 半自動指派 Semi-Auto Mode"""

dispatch_link = 'https://docs.google.com/spreadsheets/d/xxxxxxxxxxx/edit#gid=xxxxxxxx'

wb = gc.open_by_url(dispatch_link)
sheet3 = wb.worksheet('Ready_to_Dispatch')
rows3 = sheet3.get_all_values()

cell_df3 = pd.DataFrame(rows3[1:],columns = rows3[0] )
cell_df3['司機頁面'] = '-'
for i in range(0,len(cell_df3)):
  cell_df3['司機頁面'][i] = 'xxxxxxxxxx' + str(cell_df3['指派司機'][i]) + '/edit'
cell_df3

# 批次指派訂單

from selenium import webdriver
import datetime
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless') #set options to be headless
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
ds = webdriver.Chrome(chrome_options=chrome_options)

ds.get('xxxxxxxxx')  
ds.find_element_by_id("admin_user_email").send_keys(Admin_User_Email)            # Admin User Email
ds.find_element_by_id("admin_user_password").send_keys(Admin_User_Password)      # Admin User Password
ds.find_element_by_xpath('//*[@id="admin_user_submit_action"]/input').click()
time.sleep(3)
  
for i in range(0,len(cell_df3)):
  try:
    ds.get('xxxxxxx')
    time.sleep(1)
    ds.find_element_by_xpath('//*[@id="order_order_request_id"]').send_keys(cell_df3['訂單編號'][i])
    ds.find_element_by_xpath('//*[@id="order_driver_id"]').send_keys(cell_df3['指派司機'][i])
    ds.find_element_by_xpath('//*[@id="order_submit_action"]/input').click()
    time.sleep(1)

    print(cell_df3['訂單編號'][i],"已指派")
  except:
    continue

# 批次發送Intercom訊息
dss = webdriver.Chrome(chrome_options=chrome_options)
dss.get('https://app.intercom.com/a/apps/xxxxxxxx') 
time.sleep(5) 
dss.find_element_by_xpath('//*[@id="admin_email"]').send_keys(Admin_User_Email2)
dss.find_element_by_xpath('//*[@id="admin_password"]').send_keys(Admin_User_Password2)
dss.find_element_by_xpath('//*[@id="new_admin"]/div[11]/button').click()
time.sleep(3)
  
for i in range(0,len(cell_df3)):
  try:
    dss.get(cell_df3['Intercom網址'][i])
    time.sleep(5)
    try:
      dss.find_element_by_id('ember705').click()
      pass
    except:
      dss.find_element_by_id('ember688').click()
      pass

    try:
      dss.find_element_by_id('ember772').clear()
      dss.find_element_by_id('ember772').send_keys(cell_df3['訊息內容'][i])
      pass
    except:
      dss.find_element_by_id('ember757').clear()
      dss.find_element_by_id('ember757').send_keys(cell_df3['訊息內容'][i])
      pass

    try:
      dss.find_element_by_id('ember806').click()
      pass
    except:
      dss.find_element_by_id('ember791').click()
      pass
    
    time.sleep(2)

    print(cell_df3['指派司機'][i],"已傳訊")
  except:
    continue